---
- name: Copy systemd service
  become: yes
  template:
    src: "odoo.service.j2"
    dest: "/etc/systemd/system/odoo.service"
    mode: 02775
    owner: "{{ odoo_role_odoo_user }}"
    group: "{{ odoo_role_odoo_group }}"

- name: Enable service
  become: yes
  systemd:
    name: odoo.service
    enabled: yes
    state: started
    daemon_reload: yes

- name: Restart Odoo service
  become: yes
  service:
    name: odoo
    state: restarted
