---
- name:  Create "{{ odoo_role_odoo_group }}" group
  become: yes
  group:
    name: "{{ odoo_role_odoo_group }}"
    state: present

- name: Create "{{ odoo_role_odoo_user }}" user
  become: yes
  user:
    name: "{{ odoo_role_odoo_user }}"
    groups: "{{ odoo_role_odoo_group }}"
    group: "{{ odoo_role_odoo_group }}"
    append: yes
    state: present
    shell: /bin/bash

- name: "Create sudoers config for {{ odoo_role_odoo_user }} user"
  become: yes
  template:
    dest: "/etc/sudoers.d/{{ odoo_role_odoo_user }}"
    mode: 0440
    owner: root
    group: root
    src: sudoers.odoo
    validate: "/usr/sbin/visudo -cf %s"
