---
# Odoo from the Odoo Nightly: http://nightly.odoo.com/
- name: Download Odoo
  get_url:
    url: "{{ odoo_role_odoo_url }}"
    dest: "{{ odoo_role_odoo_download_path }}"
    owner: "{{ odoo_role_odoo_user }}"
    group: "{{ odoo_role_odoo_group }}"
  when: odoo_role_odoo_edition == "odoo"

- name: Uncompress downloaded Odoo
  unarchive:
    src: "{{ odoo_role_odoo_download_path }}"
    dest: "{{ odoo_role_odoo_path }}"
    remote_src: yes
    owner: "{{ odoo_role_odoo_user }}"
    group: "{{ odoo_role_odoo_group }}"
    extra_opts: [--strip-components=1]
    creates: "{{ odoo_role_odoo_path }}/setup.py"
  when: odoo_role_odoo_edition  == "odoo"

# Odoo from the OCA/OCB repository: https://github.com/OCA/OCB
- name: "Git clone git reference {{ odoo_role_odoo_git_ref }}"
  become_user: "{{ odoo_role_odoo_user }}"
  git:
    repo: "{{ odoo_role_odoo_git_url }}"
    dest: "{{ odoo_role_odoo_path }}"
    version: "{{ odoo_role_odoo_git_ref }}"
    depth: 1
  when: odoo_role_odoo_edition == "oca"
