---
- name: Download Odoo
  get_url:
    url: "{{ odoo_url }}"
    dest: "{{ odoo_download_path }}"
    owner: "{{ odoo_default_user }}"
    group: "{{  odoo_default_group }}"
  when: odoo_code_from == "nightly"

- name: Uncompress downloaded Odoo
  unarchive:
    src: "{{ odoo_download_path }}"
    dest: "{{ odoo_path }}"
    remote_src: yes
    owner: "{{ odoo_default_user }}"
    group: "{{ odoo_default_group }}"
    extra_opts: [--strip-components=1]
    creates: "{{ odoo_path }}/setup.py"
  when: odoo_code_from == "nightly"

- name: "Git clone Odoo branch {{ odoo_version }}"
  become_user: "{{ odoo_default_user }}"
  git:
    repo: "{{ odoo_git_url }}"
    dest: "{{ odoo_path }}"
    version: "{{ odoo_version }}"
    depth: 1
  when: odoo_code_from == "git"

- name: "Git checkout to the head {{ odoo_head }}"
  become_user: "{{ odoo_default_user }}"
  git:
    clone: no
    repo: "{{ odoo_git_url }}"
    dest: "{{ odoo_path }}"
    version: "{{ odoo_head }}"
  when: odoo_code_from == "git"
