---
# Odoo from the Odoo Nightly: http://nightly.odoo.com/
- name: Download an Odoo release tar packet
  block:
  - name: Ensure download path exists
    file:
      path: "{{ odoo_role_odoo_download_path  | dirname }}"
      state: directory
      owner: "{{ odoo_role_odoo_user }}"
      group: "{{ odoo_role_odoo_group }}"

  - name: Download Odoo
    get_url:
      url: "{{ odoo_role_odoo_url }}"
      dest: "{{ odoo_role_odoo_download_path }}"
      owner: "{{ odoo_role_odoo_user }}"
      group: "{{ odoo_role_odoo_group }}"
    register: odoo_role_desired_download

  - name: Uncompress downloaded Odoo
    unarchive:
      src: "{{ odoo_role_odoo_download_path }}"
      dest: "{{ odoo_role_odoo_path }}"
      remote_src: yes
      owner: "{{ odoo_role_odoo_user }}"
      group: "{{ odoo_role_odoo_group }}"
      extra_opts: [--strip-components=1]
    when: odoo_role_desired_download.changed

  when: odoo_role_download_strategy == "tar"


# Odoo from the OCA/OCB repository: https://github.com/OCA/OCB
- name: "Git clone git reference {{ odoo_role_odoo_git_ref }}"
  become_user: "{{ odoo_role_odoo_user }}"
  git:
    repo: "{{ odoo_role_odoo_git_url }}"
    dest: "{{ odoo_role_odoo_path }}"
    version: "{{ odoo_role_odoo_git_ref }}"
    depth: 1
    force: yes

  when: odoo_role_download_strategy == "git"

