---
- name: Install virtualenv package
  become: yes
  apt:
    update_cache: yes
    pkg: python3-venv
    state: present

- name: Create virtualenv directory
  become: yes
  file:
    path: "{{ odoo_role_odoo_venv_path }}"
    state: directory
    mode: 02775
    group: "{{ odoo_role_odoo_group }}"

- name: Check if virtualenv is already created
  stat:
    path: "{{ odoo_role_odoo_venv_path }}/bin"
  register: env

- name: Manually create the initial virtualenv
  command: "python3 -m venv {{ odoo_role_odoo_venv_path }}"
  when: env.stat.isdir is undefined

- name: Change virtualenv permissions
  become: yes
  file:
    path: "{{ odoo_role_odoo_venv_path }}"
    owner: odoo
    group: "{{ odoo_role_odoo_group }}"
    mode: 02775
    recurse: yes
